<?php
$meta = ['title' => 'Portafolio de diseño web y ecommerce | Go Creative Chile', 'description' => 'Conoce proyectos de diseño web, tiendas online y sitios corporativos desarrollados para empresas y marcas en Chile.', 'path' => '/portafolio/', 'image' => '/assets/img/portfolio/1.webp'];
$active = 'portafolio';
require dirname(__DIR__) . '/includes/header.php';
?>
<section class="inner-hero"><div class="container"><div class="breadcrumbs"><a href="/">Inicio</a><span>/</span><span>Portafolio</span></div><div class="inner-hero__grid"><div><p class="eyebrow"><span></span> Proyectos seleccionados</p><h1>Diseño claro, identidad propia y experiencias que se sienten <em>profesionales.</em></h1><p class="inner-hero__lead">Una selección de sitios corporativos, tiendas online y proyectos digitales creados para diferentes industrias.</p></div><div class="inner-hero__aside"><p>Cada solución se adapta al mercado, al contenido y al objetivo comercial de su marca.</p><a class="text-link" href="/contacto/">Quiero un proyecto así <span>→</span></a></div></div></div></section>
<section class="section"><div class="container"><div class="portfolio-page-grid">
<?php foreach ($portfolioItems as $item): ?><article class="portfolio-card" data-reveal><div class="portfolio-card__image"><img src="/assets/img/portfolio/<?= e($item['image']) ?>" alt="Proyecto web <?= e($item['name']) ?>" width="960" height="515" loading="lazy"></div><div class="portfolio-card__body"><div><span><?= e($item['type']) ?></span><h2 style="font-size:1.35rem;margin:5px 0 0"><?= e($item['name']) ?></h2><p><?= e($item['description']) ?></p></div><span class="portfolio-card__arrow">↗</span></div></article><?php endforeach; ?>
</div></div></section>
<section class="section section--dark"><div class="container"><div class="section-heading section-heading--split"><div><p class="eyebrow"><span></span> Criterio de diseño</p><h2>Cada proyecto parte desde cero.</h2></div><p style="color:#aebbc7">No repetimos una plantilla sin contexto. Elegimos jerarquías, color, ritmo, contenido y funciones según la marca y sus usuarios.</p></div><div class="stats-grid"><div class="stat"><strong>8</strong><span>Proyectos destacados</span></div><div class="stat"><strong>100%</strong><span>Responsive</span></div><div class="stat"><strong>SEO</strong><span>Base técnica</span></div><div class="stat"><strong>Chile</strong><span>Cobertura nacional</span></div></div></div></section>
<section class="cta-band"><div class="container cta-band__inner"><div><h2>Tu empresa puede ser nuestro próximo proyecto destacado.</h2><p>Hablemos de tu objetivo, contenido y alcance.</p></div><div class="cta-band__actions"><a class="button button--lime" href="/contacto/">Iniciar proyecto <span>↗</span></a></div></div></section>
<?php require dirname(__DIR__) . '/includes/footer.php'; ?>
