<?php
$meta = ['title' => 'Diseño creativo digital e identidad visual | Go Creative Chile', 'description' => 'Diseño de identidad visual, banners, gráficas y recursos digitales de alto impacto para fortalecer marcas y campañas.', 'path' => '/diseno-creativo-digital/'];
$active = 'servicios';
require dirname(__DIR__) . '/includes/header.php';
?>
<section class="inner-hero"><div class="container"><div class="breadcrumbs"><a href="/">Inicio</a><span>/</span><a href="/servicios/">Servicios</a><span>/</span><span>Diseño creativo</span></div><div class="inner-hero__grid"><div><p class="eyebrow"><span></span> Diseño creativo digital</p><h1>Una marca coherente se reconoce, se recuerda y <em>genera confianza.</em></h1><p class="inner-hero__lead">Creamos identidades visuales, banners, gráficas y recursos digitales que conectan con tu público y fortalecen tu presencia online.</p></div><div class="inner-hero__aside"><p>El diseño parte por entender el propósito, el público y los espacios donde la marca necesita verse consistente.</p><a class="text-link" href="/contacto/">Solicitar propuesta <span>→</span></a></div></div></div></section>
<section class="section"><div class="container"><div class="section-heading section-heading--split"><div><p class="eyebrow eyebrow--dark"><span></span> Sistema visual</p><h2>Diseño que ordena la comunicación y mejora la percepción.</h2></div><p>Construimos recursos útiles para web, redes sociales, campañas y documentos, manteniendo una línea gráfica reconocible.</p></div><div class="feature-grid"><article class="feature-card"><div class="feature-card__icon">01</div><h3>Identidad visual</h3><p>Paleta, tipografías, criterios gráficos y aplicaciones esenciales para tu marca.</p></article><article class="feature-card"><div class="feature-card__icon">02</div><h3>Contenido digital</h3><p>Banners, portadas, piezas de campaña, gráficas informativas y recursos para redes.</p></article><article class="feature-card"><div class="feature-card__icon">03</div><h3>Diseño web coherente</h3><p>Interfaces y contenidos visuales alineados con la personalidad y los objetivos del negocio.</p></article></div></div></section>
<section class="split-media"><div class="split-media__image"><img src="/assets/img/parallax-strategy.webp" alt="Equipo creativo planificando la composición y el lenguaje visual de una marca" width="1920" height="768" loading="lazy" decoding="async"></div><div class="split-media__content"><p class="eyebrow"><span></span> Creatividad con intención</p><h2>Cada decisión visual debe ayudar a comunicar.</h2><p>Color, fotografía, composición y jerarquía trabajan juntos para presentar mejor tu empresa y facilitar que el público entienda su propuesta.</p><a class="text-link" href="/portafolio/">Ver proyectos <span>→</span></a></div></section>
<section class="cta-band"><div class="container cta-band__inner"><div><h2>Dale consistencia a tu presencia digital.</h2><p>Cuéntanos qué piezas necesitas y dónde se utilizarán.</p></div><div class="cta-band__actions"><a class="button button--lime" href="/contacto/">Conversar sobre diseño <span>↗</span></a></div></div></section>
<?php require dirname(__DIR__) . '/includes/footer.php'; ?>
