<?php
$meta = ['title' => 'Agencia de diseño web y soluciones digitales | Go Creative', 'description' => 'Conoce Go Creative Chile: estrategia, diseño y tecnología para crear páginas web, sistemas y soluciones digitales de alto nivel.', 'path' => '/nosotros/'];
$active = 'nosotros';
require dirname(__DIR__) . '/includes/header.php';
?>
<section class="inner-hero"><div class="container"><div class="breadcrumbs"><a href="/">Inicio</a><span>/</span><span>Nosotros</span></div><div class="inner-hero__grid"><div><p class="eyebrow"><span></span> Go Creative Chile</p><h1>Creatividad para destacar. Tecnología para <em>avanzar.</em></h1><p class="inner-hero__lead">Ayudamos a empresas y emprendedores a construir una presencia digital profesional y a resolver procesos con soluciones claras, seguras y personalizadas.</p></div><div class="inner-hero__aside"><p>Más de 1.500 clientes y proyectos respaldan una forma de trabajar basada en escucha, comunicación y resultados útiles.</p><a class="text-link" href="/portafolio/">Conocer trabajos <span>→</span></a></div></div></div></section>
<section class="split-media"><div class="split-media__image"><img src="/assets/img/about-bg.webp" alt="Equipo Go Creative desarrollando una estrategia digital" width="1800" height="940"></div><div class="split-media__content"><p class="eyebrow"><span></span> Nuestro propósito</p><h2>Hacer que la tecnología se sienta más simple.</h2><p>Convertimos información dispersa, ideas y necesidades operativas en experiencias digitales ordenadas. El resultado debe verse profesional, funcionar correctamente y ser fácil de usar.</p><p>Trabajamos desde Los Ángeles, Biobío, con atención para empresas de todo Chile.</p></div></section>
<section class="section"><div class="container content-grid"><div class="content-grid__intro"><p class="eyebrow eyebrow--dark"><span></span> Cómo trabajamos</p><h2>Un proceso visible y colaborativo.</h2><p>La comunicación constante evita sorpresas y permite tomar mejores decisiones durante el proyecto.</p></div><div class="content-stack"><article class="content-item"><span>01</span><div><h3>Escuchamos el contexto</h3><p>Entendemos objetivos, usuarios, restricciones, problemas y prioridades antes de diseñar.</p></div></article><article class="content-item"><span>02</span><div><h3>Ordenamos el alcance</h3><p>Definimos páginas, funciones, datos, etapas, entregables y responsabilidades.</p></div></article><article class="content-item"><span>03</span><div><h3>Diseñamos y construimos</h3><p>Trabajamos una interfaz coherente, responsive y alineada con el resultado esperado.</p></div></article><article class="content-item"><span>04</span><div><h3>Probamos y acompañamos</h3><p>Validamos, ajustamos, publicamos y capacitamos para una puesta en marcha segura.</p></div></article></div></div></section>
<section class="section section--mist"><div class="container"><div class="section-heading section-heading--center"><p class="eyebrow eyebrow--dark"><span></span> Lo que nos define</p><h2>Calidad visible y utilidad real.</h2></div><div class="feature-grid"><article class="feature-card"><div class="feature-card__icon">✦</div><h3>Diseño con criterio</h3><p>Estética moderna, jerarquía clara y una identidad alineada con cada empresa.</p></article><article class="feature-card"><div class="feature-card__icon">✓</div><h3>Comunicación transparente</h3><p>Actualizaciones, revisiones y decisiones compartidas durante el desarrollo.</p></article><article class="feature-card"><div class="feature-card__icon">↗</div><h3>Base para crecer</h3><p>Soluciones que permiten sumar contenidos, módulos e integraciones en el futuro.</p></article></div></div></section>
<section class="cta-band"><div class="container cta-band__inner"><div><h2>Conversemos sobre tu próximo proyecto.</h2><p>Te ayudaremos a convertir una necesidad en un plan claro.</p></div><div class="cta-band__actions"><a class="button button--lime" href="/contacto/">Hablar con Go Creative <span>↗</span></a></div></div></section>
<?php require dirname(__DIR__) . '/includes/footer.php'; ?>
