<?php
$meta = ['title' => 'Automatización de procesos para empresas | Go Creative Chile', 'description' => 'Automatizamos formularios, tareas, aprobaciones, alertas, correos, documentos, datos y reportes para reducir trabajo manual.', 'path' => '/automatizacion/'];
$active = 'servicios';
require dirname(__DIR__) . '/includes/header.php';
?>
<section class="inner-hero"><div class="container"><div class="breadcrumbs"><a href="/">Inicio</a><span>/</span><a href="/servicios/">Servicios</a><span>/</span><span>Automatización</span></div><div class="inner-hero__grid"><div><p class="eyebrow"><span></span> Menos trabajo manual</p><h1>Recupera horas y reduce errores con procesos <em>conectados.</em></h1><p class="inner-hero__lead">Automatizamos tareas repetitivas, notificaciones, documentos y traspasos de información para que tu equipo se concentre en decisiones y clientes.</p></div><div class="inner-hero__aside"><p>Primero revisamos el flujo actual y confirmamos qué partes conviene automatizar, en qué orden y con qué controles.</p><a class="text-link" href="/contacto/">Revisar un proceso <span>→</span></a></div></div></div></section>
<section class="section"><div class="container"><div class="section-heading section-heading--split"><div><p class="eyebrow eyebrow--dark"><span></span> Casos de uso</p><h2>La información avanza sin depender de tareas repetidas.</h2></div><p>Conectamos formularios, correos, bases de datos y plataformas para evitar doble digitación y mejorar la trazabilidad.</p></div><div class="feature-grid"><article class="feature-card"><div class="feature-card__icon">⚡</div><h3>Flujos y aprobaciones</h3><p>Asignación de responsables, cambios de estado, validaciones y recordatorios automáticos.</p></article><article class="feature-card"><div class="feature-card__icon">✉</div><h3>Comunicaciones</h3><p>Correos, confirmaciones, alertas y mensajes que se activan según eventos y reglas.</p></article><article class="feature-card"><div class="feature-card__icon">▤</div><h3>Documentos y datos</h3><p>Generación de archivos, actualización de registros, sincronización y reportes programados.</p></article></div></div></section>
<section class="section section--dark"><div class="container content-grid"><div class="content-grid__intro"><p class="eyebrow"><span></span> Método</p><h2>Automatizamos con control, no a ciegas.</h2><p style="color:#aebbc7">Cada flujo incluye criterios, responsables, excepciones y puntos de revisión para evitar que la velocidad sacrifique la calidad.</p></div><ol class="process-list"><li><span>01</span><div><h3>Mapear el proceso</h3><p>Entradas, tareas, responsables, tiempos y problemas.</p></div></li><li><span>02</span><div><h3>Definir reglas</h3><p>Eventos, condiciones, acciones, alertas y excepciones.</p></div></li><li><span>03</span><div><h3>Conectar herramientas</h3><p>Formularios, sistemas, correo, datos y documentos.</p></div></li><li><span>04</span><div><h3>Medir y mejorar</h3><p>Trazabilidad, resultados, errores y nuevas oportunidades.</p></div></li></ol></div></section>
<section class="cta-band"><div class="container cta-band__inner"><div><h2>¿Qué tarea consume horas todas las semanas?</h2><p>Ese puede ser el mejor lugar para comenzar.</p></div><div class="cta-band__actions"><a class="button button--lime" href="/contacto/">Quiero automatizar <span>↗</span></a></div></div></section>
<?php require dirname(__DIR__) . '/includes/footer.php'; ?>
