<?php
$meta = ['title' => 'Diseño y desarrollo de páginas web en Chile | Go Creative', 'description' => 'Páginas web profesionales, rápidas, seguras, responsive y optimizadas para SEO. Diseño web para empresas y emprendedores en Chile.', 'path' => '/diseno-web-chile/'];
$active = 'web';
require dirname(__DIR__) . '/includes/header.php';
?>
<section class="inner-hero"><div class="container"><div class="breadcrumbs"><a href="/">Inicio</a><span>/</span><a href="/servicios/">Servicios</a><span>/</span><span>Desarrollo web</span></div><div class="inner-hero__grid"><div><p class="eyebrow"><span></span> Diseño web profesional</p><h1>Tu empresa merece una web que transmita <em>confianza.</em></h1><p class="inner-hero__lead">Creamos sitios modernos, rápidos, seguros y adaptados a celulares, con mensajes claros y una estructura preparada para Google.</p></div><div class="inner-hero__aside"><p>Diseño responsive, contenidos comerciales, SEO base, WhatsApp, formularios, dominio, hosting, correos corporativos y capacitación según el plan.</p><a class="text-link" href="/contacto/">Cotizar página web <span>→</span></a></div></div></div></section>
<section class="section"><div class="container"><div class="section-heading section-heading--split"><div><p class="eyebrow eyebrow--dark"><span></span> Más que una portada</p><h2>Una web trabaja incluso cuando tu empresa está cerrada.</h2></div><p>Presenta servicios, responde dudas, demuestra experiencia y recibe consultas las 24 horas. Cada bloque guía al visitante hacia una acción concreta.</p></div><div class="feature-grid"><article class="feature-card" data-reveal><div class="feature-card__icon">01</div><h3>Imagen profesional</h3><p>Una estética coherente y actual que mejora la percepción de tu empresa desde el primer vistazo.</p></article><article class="feature-card" data-reveal><div class="feature-card__icon">02</div><h3>Contenido que orienta</h3><p>Textos, jerarquías y llamados a la acción para que el cliente entienda rápido qué haces.</p></article><article class="feature-card" data-reveal><div class="feature-card__icon">03</div><h3>Base SEO sólida</h3><p>Metadatos, estructura semántica, enlaces internos, imágenes optimizadas y datos estructurados.</p></article></div></div></section>
<section class="section section--mist"><div class="container content-grid"><div class="content-grid__intro"><p class="eyebrow eyebrow--dark"><span></span> Incluido según alcance</p><h2>Todo lo necesario para publicar con seguridad.</h2><p>Organizamos diseño, contenido y configuración técnica para entregar una experiencia profesional y fácil de mantener.</p></div><ul class="check-grid"><li>Arquitectura de contenidos</li><li>Diseño responsive personalizado</li><li>Páginas internas y navegación</li><li>Textos comerciales principales</li><li>Formulario y WhatsApp</li><li>SEO técnico y on-page base</li><li>Optimización de imágenes</li><li>Google Analytics opcional</li><li>Dominio, hosting y SSL</li><li>Correos corporativos</li><li>Panel autoadministrable</li><li>Capacitación y soporte inicial</li></ul></div></section>
<section class="section"><div class="container"><div class="section-heading section-heading--center"><p class="eyebrow eyebrow--dark"><span></span> Alternativas</p><h2>Elige una base y la adaptamos a tu negocio.</h2><p>Los valores son referenciales y pueden cambiar según páginas, contenidos, funciones e integraciones.</p></div><div class="plan-grid"><article class="plan-card"><span class="plan-card__tag">Oferta limitada</span><h3>One Page Express</h3><p>Una página compacta para comenzar rápido.</p><div class="price"><small>desde</small><strong>$55.000</strong><span>pago único</span></div><ul><li>Hasta 5 bloques</li><li>Diseño responsive</li><li>WhatsApp y formulario</li><li>SEO inicial</li></ul><a class="button button--outline" href="<?= e(whatsapp_url('Hola, quiero consultar disponibilidad para One Page Express.')) ?>" target="_blank" rel="noopener">Consultar cupo</a></article><article class="plan-card plan-card--featured"><span class="plan-card__tag">Recomendado</span><h3>Web Profesional</h3><p>Para empresas de servicios con contenido y páginas internas.</p><div class="price"><small>desde</small><strong>$220.000</strong><span>pago único</span></div><ul><li>Diseño personalizado</li><li>Páginas internas</li><li>Autoadministrable</li><li>SEO y capacitación</li></ul><a class="button button--lime" href="/contacto/">Cotizar plan</a></article><article class="plan-card"><span class="plan-card__tag">Mayor alcance</span><h3>Web Corporativa</h3><p>Para empresas con múltiples áreas y contenidos.</p><div class="price"><small>desde</small><strong>$560.000</strong><span>pago único</span></div><ul><li>Arquitectura ampliada</li><li>Diseño corporativo</li><li>SEO base avanzado</li><li>Soporte inicial</li></ul><a class="button button--outline" href="/contacto/">Solicitar propuesta</a></article></div></div></section>
<section class="cta-band"><div class="container cta-band__inner"><div><p class="eyebrow"><span></span> Da el siguiente paso</p><h2>Construyamos una presencia digital a la altura de tu empresa.</h2></div><div class="cta-band__actions"><a class="button button--lime" href="/contacto/">Cotizar mi página web <span>↗</span></a></div></div></section>
<?php require dirname(__DIR__) . '/includes/footer.php'; ?>
