<?php
$meta = ['title' => 'Soporte técnico, mantenimiento y migración web | Go Creative', 'description' => 'Soporte técnico remoto, mantenimiento, recuperación, optimización de velocidad y migración segura de sitios web para empresas en Chile.', 'path' => '/soporte-tecnico/'];
$active = 'servicios';
require dirname(__DIR__) . '/includes/header.php';
?>
<section class="inner-hero"><div class="container"><div class="breadcrumbs"><a href="/">Inicio</a><span>/</span><a href="/servicios/">Servicios</a><span>/</span><span>Soporte técnico</span></div><div class="inner-hero__grid"><div><p class="eyebrow"><span></span> Continuidad y seguridad</p><h1>Recuperamos, optimizamos y migramos tu sitio <em>con cuidado.</em></h1><p class="inner-hero__lead">Si tu página está lenta, presenta errores o necesita cambiar de hosting, revisamos el problema y definimos una solución clara antes de intervenir.</p></div><div class="inner-hero__aside"><p>Atención remota, diagnóstico, respaldo y acciones documentadas para reducir riesgos y recuperar estabilidad.</p><a class="text-link" href="/contacto/">Solicitar diagnóstico <span>→</span></a></div></div></div></section>
<section class="section"><div class="container"><div class="feature-grid"><article class="feature-card"><div class="feature-card__icon">01</div><h3>Web lenta o inestable</h3><p>Optimizamos imágenes, código, caché y configuración para mejorar velocidad y estabilidad.</p></article><article class="feature-card"><div class="feature-card__icon">02</div><h3>Errores o sitio caído</h3><p>Diagnosticamos fallas, enlaces rotos, problemas de carga y conflictos técnicos.</p></article><article class="feature-card"><div class="feature-card__icon">03</div><h3>Migración segura</h3><p>Trasladamos web, base de datos, correos, dominio y SSL minimizando interrupciones.</p></article></div></div></section>
<section class="section section--mist"><div class="container content-grid"><div class="content-grid__intro"><p class="eyebrow eyebrow--dark"><span></span> Soporte planificado</p><h2>También prevenimos problemas antes de que aparezcan.</h2><p>Un mantenimiento regular prolonga la vida útil del sitio y reduce el riesgo de fallas acumuladas.</p></div><ul class="check-grid"><li>Copias de seguridad</li><li>Actualizaciones controladas</li><li>Revisión de seguridad</li><li>Optimización de velocidad</li><li>Monitoreo básico</li><li>Corrección de enlaces</li><li>Ajustes de contenido</li><li>Soporte remoto</li></ul></div></section>
<section class="cta-band"><div class="container cta-band__inner"><div><h2>Cuéntanos qué está fallando.</h2><p>Revisaremos los síntomas, el nivel de urgencia y el acceso necesario para diagnosticar.</p></div><div class="cta-band__actions"><a class="button button--lime" href="/contacto/">Solicitar soporte <span>↗</span></a></div></div></section>
<?php require dirname(__DIR__) . '/includes/footer.php'; ?>
