<?php
$meta = ['title' => 'Diseño de tiendas online y ecommerce en Chile | Go Creative', 'description' => 'Creamos tiendas online profesionales con catálogo, carrito, pagos, envíos, inventario, pedidos y panel de administración.', 'path' => '/tiendas-online/'];
$active = 'servicios';
require dirname(__DIR__) . '/includes/header.php';
?>
<section class="inner-hero"><div class="container"><div class="breadcrumbs"><a href="/">Inicio</a><span>/</span><a href="/servicios/">Servicios</a><span>/</span><span>Tiendas online</span></div><div class="inner-hero__grid"><div><p class="eyebrow"><span></span> Ecommerce</p><h1>Una tienda online preparada para <em>vender desde el día uno.</em></h1><p class="inner-hero__lead">Creamos una experiencia de compra ordenada, confiable y fácil de administrar, desde el catálogo hasta la entrega.</p></div><div class="inner-hero__aside"><p>Productos, categorías, filtros, carrito, pagos, envíos, pedidos, inventario y capacitación reunidos en una solución adaptable.</p><a class="text-link" href="/contacto/">Cotizar ecommerce <span>→</span></a></div></div></div></section>
<section class="section"><div class="container"><div class="section-heading section-heading--split"><div><p class="eyebrow eyebrow--dark"><span></span> Experiencia completa</p><h2>Cada etapa de compra debe sentirse simple.</h2></div><p>Reducimos dudas, ordenamos información y configuramos un recorrido claro para que el cliente encuentre, compare, pague y reciba.</p></div><div class="feature-grid"><article class="feature-card"><div class="feature-card__icon">01</div><h3>Catálogo y productos</h3><p>Fichas con fotos, videos, precios, variaciones, stock, categorías, marcas y filtros.</p></article><article class="feature-card"><div class="feature-card__icon">02</div><h3>Compra y pago</h3><p>Carrito, checkout rápido, tarjetas, transferencias y otros medios compatibles.</p></article><article class="feature-card"><div class="feature-card__icon">03</div><h3>Operación</h3><p>Pedidos, inventario, estados, notificaciones, tarifas de envío y reglas de despacho.</p></article></div></div></section>
<section class="section section--mist"><div class="container content-grid"><div class="content-grid__intro"><p class="eyebrow eyebrow--dark"><span></span> Alcance funcional</p><h2>Una tienda que también simplifica la administración.</h2><p>Configuramos la base comercial y operativa para que tu equipo tenga control después del lanzamiento.</p></div><ul class="check-grid"><li>Productos y variaciones</li><li>Categorías, marcas y filtros</li><li>Stock e inventario</li><li>Carrito y checkout</li><li>Pasarelas de pago</li><li>Transferencia bancaria</li><li>Tarifas y zonas de envío</li><li>Gestión de pedidos</li><li>Cupones y promociones</li><li>Correos transaccionales</li><li>Políticas y seguridad</li><li>Capacitación de uso</li></ul></div></section>
<section class="section section--dark"><div class="container"><div class="section-heading section-heading--split"><div><p class="eyebrow"><span></span> Plan ecommerce</p><h2>Web de tienda desde $560.000.</h2></div><p class="section-copy--muted">El valor definitivo depende de la cantidad de productos, integraciones, reglas de despacho, diseño y necesidades de inventario.</p></div><div class="stats-grid"><div class="stat"><strong>100%</strong><span>Responsive</span></div><div class="stat"><strong>24/7</strong><span>Catálogo disponible</span></div><div class="stat"><strong>1</strong><span>Panel central</span></div><div class="stat"><strong>SEO</strong><span>Base incluida</span></div></div></div></section>
<section class="cta-band"><div class="container cta-band__inner"><div><h2>Vende online con una experiencia profesional.</h2><p>Cuéntanos qué vendes, cuántos productos tienes y cómo realizas tus despachos.</p></div><div class="cta-band__actions"><a class="button button--lime" href="/contacto/">Cotizar tienda online <span>↗</span></a></div></div></section>
<?php require dirname(__DIR__) . '/includes/footer.php'; ?>
