<?php if ($errors !== []): ?><div class="alert alert-danger"><strong>Revisa la cotización:</strong><ul class="mb-0 mt-2"><?php foreach ($errors as $error): ?><li><?= e($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?>
<form method="post" action="<?= e($formAction) ?>" data-quote-form>
<?= csrf_field() ?>
<div class="row g-4">
    <div class="col-xl-8">
        <section class="form-section"><div class="form-section__heading"><h2>Cliente</h2><p>Datos que aparecerán en el PDF y en el correo.</p></div><div class="row g-3">
            <div class="col-md-6"><label class="form-label" for="customer_name">NOMBRE *</label><input class="form-control" id="customer_name" name="customer_name" value="<?= e($form['customer_name']) ?>" maxlength="100" required autofocus></div>
            <div class="col-md-6"><label class="form-label" for="customer_email">CORREO *</label><input class="form-control" id="customer_email" name="customer_email" type="email" value="<?= e($form['customer_email']) ?>" maxlength="190" required></div>
            <div class="col-md-6"><label class="form-label" for="customer_company">EMPRESA</label><input class="form-control" id="customer_company" name="customer_company" value="<?= e($form['customer_company']) ?>" maxlength="150"></div>
            <div class="col-md-3"><label class="form-label" for="customer_tax_id">RUT</label><input class="form-control" id="customer_tax_id" name="customer_tax_id" value="<?= e($form['customer_tax_id']) ?>" maxlength="30"></div>
            <div class="col-md-3"><label class="form-label" for="customer_phone">TELÉFONO</label><input class="form-control" id="customer_phone" name="customer_phone" value="<?= e($form['customer_phone']) ?>" maxlength="30"></div>
            <div class="col-md-8"><label class="form-label" for="customer_address">DIRECCIÓN</label><input class="form-control" id="customer_address" name="customer_address" value="<?= e($form['customer_address']) ?>" maxlength="255"></div>
            <div class="col-md-4"><label class="form-label" for="customer_city">CIUDAD</label><input class="form-control" id="customer_city" name="customer_city" value="<?= e($form['customer_city']) ?>" maxlength="100"></div>
        </div></section>
        <section class="form-section"><div class="form-section__heading"><h2>Propuesta</h2><p>Un título y contexto breve hacen que la cotización se entienda mejor.</p></div><div class="row g-3">
            <div class="col-12"><label class="form-label" for="title">TÍTULO *</label><input class="form-control" id="title" name="title" value="<?= e($form['title']) ?>" maxlength="180" required></div>
            <div class="col-12"><label class="form-label" for="introduction">INTRODUCCIÓN</label><textarea class="form-control" id="introduction" name="introduction" rows="4" maxlength="1500"><?= e($form['introduction']) ?></textarea></div>
            <div class="col-md-6"><label class="form-label" for="issue_date">FECHA DE EMISIÓN</label><input class="form-control" id="issue_date" name="issue_date" type="date" value="<?= e($form['issue_date']) ?>" required></div>
            <div class="col-md-6"><label class="form-label" for="valid_until">VÁLIDA HASTA</label><input class="form-control" id="valid_until" name="valid_until" type="date" value="<?= e($form['valid_until']) ?>" required></div>
        </div></section>
        <section class="form-section quote-items-section"><div class="form-section__heading"><h2>Servicios y productos</h2><p>Agrega desde el catálogo o escribe ítems completamente personalizados.</p></div>
            <div class="quote-catalog-bar"><select class="form-select" id="quote_catalog"><option value="">Selecciona un servicio rápido</option><?php foreach ($catalog as $catalogItem): ?><option value="<?= (int) $catalogItem['id'] ?>" data-type="<?= e($catalogItem['item_type']) ?>" data-name="<?= e($catalogItem['name']) ?>" data-description="<?= e($catalogItem['description'] ?? '') ?>" data-price="<?= (int) $catalogItem['unit_price'] ?>"><?= e($catalogItem['name']) ?> · $<?= number_format((int) $catalogItem['unit_price'], 0, ',', '.') ?></option><?php endforeach; ?></select><button class="btn btn-dark" type="button" data-add-catalog>Agregar</button><?php if (can('catalog.manage')): ?><a class="btn btn-outline-dark" href="<?= e(admin_url('cotizaciones/catalogo.php')) ?>">Editar catálogo</a><?php endif; ?></div>
            <div class="quote-items" data-quote-items>
            <?php foreach ($items as $item): ?><article class="quote-item" data-quote-item><div class="quote-item__head"><strong>Ítem</strong><button type="button" data-remove-item aria-label="Quitar ítem">×</button></div><div class="row g-2"><div class="col-md-3"><label class="form-label">TIPO</label><select class="form-select" name="item_type[]"><option value="service"<?= $item['item_type'] === 'service' ? ' selected' : '' ?>>Servicio</option><option value="product"<?= $item['item_type'] === 'product' ? ' selected' : '' ?>>Producto</option></select></div><div class="col-md-9"><label class="form-label">NOMBRE *</label><input class="form-control" name="name[]" value="<?= e($item['name']) ?>" maxlength="180" required></div><div class="col-12"><label class="form-label">DESCRIPCIÓN</label><textarea class="form-control" name="description[]" rows="2" maxlength="1000"><?= e($item['description']) ?></textarea></div><div class="col-4"><label class="form-label">CANTIDAD</label><input class="form-control" name="quantity[]" type="number" min="0.01" max="9999" step="0.01" value="<?= e((string) $item['quantity']) ?>" required></div><div class="col-8"><label class="form-label">VALOR UNITARIO</label><div class="input-group"><span class="input-group-text">$</span><input class="form-control" name="unit_price[]" type="number" min="0" max="1000000000" step="1" value="<?= e((string) $item['unit_price']) ?>" required></div></div></div></article><?php endforeach; ?>
            </div>
            <button class="btn btn-outline-dark mt-3" type="button" data-add-empty>+ Agregar ítem manual</button>
            <template id="quote-item-template"><article class="quote-item" data-quote-item><div class="quote-item__head"><strong>Ítem</strong><button type="button" data-remove-item aria-label="Quitar ítem">×</button></div><div class="row g-2"><div class="col-md-3"><label class="form-label">TIPO</label><select class="form-select" name="item_type[]"><option value="service">Servicio</option><option value="product">Producto</option></select></div><div class="col-md-9"><label class="form-label">NOMBRE *</label><input class="form-control" name="name[]" maxlength="180" required></div><div class="col-12"><label class="form-label">DESCRIPCIÓN</label><textarea class="form-control" name="description[]" rows="2" maxlength="1000"></textarea></div><div class="col-4"><label class="form-label">CANTIDAD</label><input class="form-control" name="quantity[]" type="number" min="0.01" max="9999" step="0.01" value="1" required></div><div class="col-8"><label class="form-label">VALOR UNITARIO</label><div class="input-group"><span class="input-group-text">$</span><input class="form-control" name="unit_price[]" type="number" min="0" max="1000000000" step="1" value="0" required></div></div></div></article></template>
        </section>
        <section class="form-section"><div class="form-section__heading"><h2>Condiciones y notas</h2><p>Se mostrarán al final del PDF.</p></div><div class="row g-3"><div class="col-12"><label class="form-label" for="terms">CONDICIONES COMERCIALES</label><textarea class="form-control" id="terms" name="terms" rows="5" maxlength="2000"><?= e($form['terms']) ?></textarea></div><div class="col-12"><label class="form-label" for="notes">OBSERVACIONES</label><textarea class="form-control" id="notes" name="notes" rows="3" maxlength="1500"><?= e($form['notes']) ?></textarea></div></div></section>
    </div>
    <div class="col-xl-4"><section class="admin-card quote-summary-card"><div class="admin-card__body"><span class="page-heading__eyebrow">Resumen automático</span><h2 class="h5 fw-bold">Total de la propuesta</h2><div class="quote-live-total"><span>Total estimado</span><strong data-quote-total>$0</strong></div><div class="mb-3"><label class="form-label" for="discount_amount">DESCUENTO TOTAL</label><div class="input-group"><span class="input-group-text">$</span><input class="form-control" id="discount_amount" name="discount_amount" type="number" min="0" max="1000000000" step="1" value="<?= e($form['discount_amount']) ?>"></div></div><div class="mb-3"><label class="form-label" for="tax_percent">IMPUESTO</label><select class="form-select" id="tax_percent" name="tax_percent"><option value="19"<?= $form['tax_percent'] === '19' ? ' selected' : '' ?>>Agregar IVA 19%</option><option value="0"<?= $form['tax_percent'] === '0' ? ' selected' : '' ?>>Sin IVA</option></select></div><?php if (can('quotes.send')): ?><label class="permission-item quote-send-option"><input class="form-check-input" type="checkbox" name="send_now" value="1"<?= $form['send_now'] === '1' ? ' checked' : '' ?>><span><strong>Enviar automáticamente</strong><small>Correo HTML profesional con PDF adjunto.</small></span></label><?php endif; ?><div class="d-grid gap-2 mt-4"><button class="btn btn-primary" type="submit"><?= $isEdit ? 'Guardar cotización' : 'Crear cotización' ?></button><a class="btn btn-outline-dark" href="<?= e(admin_url('cotizaciones/')) ?>">Cancelar</a></div></div></section></div>
</div>
</form>
