<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/bootstrap.php';
require_once dirname(__DIR__, 2) . '/app/Quotes/quote_helpers.php';
$currentAdmin = require_permission('quotes.view');
db()->exec("UPDATE quotes SET status = 'expired' WHERE status IN ('draft','sent') AND valid_until < CURDATE()");
$query = trim((string) ($_GET['q'] ?? '')); $status = (string) ($_GET['status'] ?? ''); $allowed = ['draft','sent','accepted','rejected','expired'];
$where = []; $params = [];
if ($query !== '') { $like = '%' . $query . '%'; $where[] = '(q.quote_number LIKE :q_number OR q.title LIKE :q_title OR c.name LIKE :q_name OR c.email LIKE :q_email)'; $params = ['q_number'=>$like,'q_title'=>$like,'q_name'=>$like,'q_email'=>$like]; }
if (in_array($status, $allowed, true)) { $where[] = 'q.status = :status'; $params['status'] = $status; }
$sql = 'SELECT q.*, c.name AS customer_name, c.company AS customer_company, c.email AS customer_email FROM quotes q INNER JOIN customers c ON c.id = q.customer_id';
if ($where) $sql .= ' WHERE ' . implode(' AND ', $where); $sql .= ' ORDER BY q.created_at DESC LIMIT 250';
$statement = db()->prepare($sql); $statement->execute($params); $quotes = $statement->fetchAll();
$stats = db()->query("SELECT COUNT(*) AS total, SUM(status='sent') AS sent, SUM(status='accepted') AS accepted, COALESCE(SUM(CASE WHEN status='accepted' THEN total ELSE 0 END),0) AS accepted_total FROM quotes")->fetch();
$pageTitle = 'Cotizaciones'; $activeMenu = 'quotes'; require dirname(__DIR__) . '/includes/header.php';
?>
<div class="page-heading"><div><span class="page-heading__eyebrow">Propuestas y ventas</span><h1>Cotizaciones</h1><p>Crea, envía y sigue propuestas comerciales con PDF profesional.</p></div><div class="d-flex gap-2 flex-wrap"><?php if (can('catalog.manage')): ?><a class="btn btn-outline-dark" href="<?= e(admin_url('cotizaciones/catalogo.php')) ?>">Catálogo</a><?php endif; ?><?php if (can('quotes.create')): ?><a class="btn btn-primary" href="<?= e(admin_url('cotizaciones/crear.php')) ?>">+ Nueva cotización</a><?php endif; ?></div></div>
<div class="row g-3 mb-4"><div class="col-6 col-xl-3"><section class="admin-card stat-card stat-card--dark"><span class="stat-card__label">Cotizaciones</span><strong class="stat-card__value"><?= (int) $stats['total'] ?></strong><span class="stat-card__note">Históricas</span></section></div><div class="col-6 col-xl-3"><section class="admin-card stat-card"><span class="stat-card__label">Enviadas</span><strong class="stat-card__value"><?= (int) $stats['sent'] ?></strong><span class="stat-card__note">Esperando respuesta</span></section></div><div class="col-6 col-xl-3"><section class="admin-card stat-card"><span class="stat-card__label">Aceptadas</span><strong class="stat-card__value"><?= (int) $stats['accepted'] ?></strong><span class="stat-card__note">Confirmadas</span></section></div><div class="col-6 col-xl-3"><section class="admin-card stat-card"><span class="stat-card__label">Valor aceptado</span><strong class="stat-card__value stat-card__value--money">$<?= number_format((int) $stats['accepted_total'], 0, ',', '.') ?></strong><span class="stat-card__note">CLP</span></section></div></div>
<section class="admin-card"><form class="filter-bar filter-bar--hosting" method="get"><input class="form-control" type="search" name="q" value="<?= e($query) ?>" placeholder="Número, cliente, correo o proyecto"><select class="form-select" name="status"><option value="">Todos los estados</option><?php foreach ($allowed as $option): $meta=quote_status_meta($option); ?><option value="<?= e($option) ?>"<?= $status===$option?' selected':'' ?>><?= e($meta['label']) ?></option><?php endforeach; ?></select><div class="d-flex gap-2"><button class="btn btn-dark">Filtrar</button><a class="btn btn-outline-dark" href="<?= e(admin_url('cotizaciones/')) ?>">Limpiar</a></div></form><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Cotización</th><th>Cliente</th><th>Proyecto</th><th>Total</th><th>Estado</th><th>Vigencia</th><th class="text-end">Acción</th></tr></thead><tbody><?php if(!$quotes):?><tr><td colspan="7" class="py-5 text-center text-secondary">No hay cotizaciones para mostrar.</td></tr><?php endif;?><?php foreach($quotes as $quote): $meta=quote_status_meta($quote['status']);?><tr><td><strong class="order-code"><?= e($quote['quote_number']) ?></strong><small class="d-block text-secondary"><?= e(format_admin_date($quote['created_at'])) ?></small></td><td><div class="user-cell"><span class="user-cell__avatar"><?= e(initials($quote['customer_name'])) ?></span><span class="user-cell__copy"><strong><?= e($quote['customer_name']) ?></strong><span><?= e($quote['customer_email']) ?></span></span></div></td><td><span class="payment-subject"><?= e($quote['title']) ?></span></td><td><strong><?= e(payment_format_amount((int)$quote['total'],$quote['currency'])) ?></strong></td><td><span class="payment-status payment-status--<?= e($meta['class']) ?>"><?= e($meta['label']) ?></span></td><td class="small text-secondary"><?= e(date('d-m-Y',strtotime($quote['valid_until']))) ?></td><td class="text-end"><a class="btn btn-sm btn-outline-dark" href="<?= e(admin_url('cotizaciones/ver.php?id='.(int)$quote['id'])) ?>">Ver propuesta</a></td></tr><?php endforeach;?></tbody></table></div></section>
<?php require dirname(__DIR__) . '/includes/footer.php'; ?>
