<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/bootstrap.php';
require_once dirname(__DIR__, 2) . '/app/Quotes/quote_helpers.php';
$currentAdmin = require_permission('quotes.view');
$id=filter_var($_GET['id']??null,FILTER_VALIDATE_INT); $quote=$id?quote_find_by_id((int)$id):null;
if(!$quote){flash('warning','La cotización no existe.');redirect_admin('cotizaciones/');}
$items=quote_items((int)$quote['id']);
$emailsStatement=db()->prepare('SELECT * FROM quote_emails WHERE quote_id=:id ORDER BY created_at DESC,id DESC');$emailsStatement->execute(['id'=>$quote['id']]);$emails=$emailsStatement->fetchAll();
$meta=quote_status_meta($quote['status']);$publicUrl=quote_public_url($quote);
$pageTitle='Detalle de cotización';$activeMenu='quotes';require dirname(__DIR__).'/includes/header.php';
?>
<div class="page-heading"><div><span class="page-heading__eyebrow"><?= e($quote['quote_number']) ?></span><h1><?= e($quote['title']) ?></h1><p><?= e($quote['customer_name']) ?> · válida hasta <?= e(date('d-m-Y',strtotime($quote['valid_until']))) ?></p></div><div class="d-flex gap-2 flex-wrap"><a class="btn btn-outline-dark" href="<?= e(admin_url('cotizaciones/')) ?>">Volver</a><?php if(can('quotes.edit')):?><a class="btn btn-dark" href="<?= e(admin_url('cotizaciones/editar.php?id='.(int)$quote['id'])) ?>">Editar</a><?php endif;?><a class="btn btn-primary" href="<?= e(admin_url('cotizaciones/pdf.php?id='.(int)$quote['id'])) ?>" target="_blank">Descargar PDF</a></div></div>
<section class="quote-hero admin-card mb-4"><div><span class="payment-status payment-status--<?= e($meta['class']) ?>"><?= e($meta['label']) ?></span><h2><?= e(payment_format_amount((int)$quote['total'],$quote['currency'])) ?></h2><p>Subtotal $<?= number_format((int)$quote['subtotal'],0,',','.') ?> · Descuento $<?= number_format((int)$quote['discount_amount'],0,',','.') ?> · IVA <?= (int)$quote['tax_percent'] ?>%</p></div><div class="quote-hero__number"><span>PROPUESTA</span><strong><?= e($quote['quote_number']) ?></strong></div></section>
<div class="row g-4"><div class="col-xl-8"><section class="admin-card mb-4"><div class="admin-card__header"><h2>Detalle económico</h2><span><?= count($items) ?> ítems</span></div><div class="quote-detail-items"><?php foreach($items as $item):?><article><span class="role-badge"><?= $item['item_type']==='product'?'Producto':'Servicio' ?></span><div><strong><?= e($item['name']) ?></strong><?php if($item['description']):?><p><?= nl2br(e($item['description'])) ?></p><?php endif;?></div><small><?= rtrim(rtrim(number_format((float)$item['quantity'],2,',','.'),'0'),',') ?> × $<?= number_format((int)$item['unit_price'],0,',','.') ?></small><b>$<?= number_format((int)$item['line_total'],0,',','.') ?></b></article><?php endforeach;?></div></section><section class="admin-card"><div class="admin-card__header"><h2>Envíos</h2><span class="status-badge status-badge--active"><?= count($emails) ?> registros</span></div><div class="admin-card__body payment-timeline"><?php if(!$emails):?><p class="text-secondary mb-0">Aún no se ha enviado por correo.</p><?php endif;?><?php foreach($emails as $email):?><article><span class="payment-timeline__dot"></span><div><strong><?= e($email['recipient']) ?></strong><small><?= e($email['status']) ?> · <?= e($email['subject']) ?></small><?php if($email['error_message']):?><p class="text-danger small mb-0"><?= e($email['error_message']) ?></p><?php endif;?></div><time><?= e(format_admin_date($email['sent_at']?:$email['created_at'])) ?></time></article><?php endforeach;?></div></section></div><div class="col-xl-4"><section class="admin-card payment-link-card mb-4"><div class="admin-card__body"><span class="page-heading__eyebrow">Enlace del cliente</span><h2 class="h5 fw-bold">Propuesta interactiva</h2><p class="text-secondary">El cliente puede verla, descargar el PDF y aceptar o rechazar.</p><div class="payment-copy"><input class="form-control" id="quote_public_url" value="<?= e($publicUrl) ?>" readonly><button class="btn btn-dark" type="button" data-copy-target="quote_public_url">Copiar</button></div><a class="btn btn-outline-dark w-100 mt-3" href="<?= e($publicUrl) ?>" target="_blank" rel="noopener">Abrir vista pública ↗</a></div></section><?php if(can('quotes.send')):?><section class="admin-card"><div class="admin-card__body"><span class="page-heading__eyebrow">Correo profesional</span><h2 class="h5 fw-bold">Enviar propuesta y PDF</h2><p class="text-secondary">El correo incluye resumen, enlace de respuesta y el documento adjunto.</p><form method="post" action="<?= e(admin_url('cotizaciones/enviar.php')) ?>" data-confirm="¿Enviar la cotización a <?= e($quote['customer_email']) ?>?"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$quote['id'] ?>"><button class="btn btn-primary w-100">Enviar por correo →</button></form></div></section><?php endif;?></div></div>
<?php require dirname(__DIR__).'/includes/footer.php'; ?>
