<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/config.php';require_once dirname(__DIR__).'/config/database/connection.php';require_once dirname(__DIR__).'/app/Quotes/quote_helpers.php';
if(session_status()===PHP_SESSION_NONE){session_name('gocreative_quote');session_set_cookie_params(['lifetime'=>0,'path'=>site_path('/cotizacion/'),'secure'=>!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off','httponly'=>true,'samesite'=>'Lax']);session_start();}
header('X-Robots-Tag: noindex, nofollow, noarchive',true);header('X-Content-Type-Options: nosniff');header('X-Frame-Options: DENY');header('Referrer-Policy: no-referrer');header("Content-Security-Policy: default-src 'self'; img-src 'self' data:; style-src 'self'; script-src 'none'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");header('Cache-Control: no-store,max-age=0');
$code=strtolower(trim((string)($_GET['codigo']??'')));$quote=null;$items=[];$serviceError=false;
try{$quote=quote_find_by_public_key($code);if($quote)$items=quote_items((int)$quote['id']);}catch(Throwable $exception){error_log('Error vista pública cotización: '.$exception->getMessage());$serviceError=true;}
if(!$quote)http_response_code($serviceError?503:404);
if(empty($_SESSION['quote_csrf']))$_SESSION['quote_csrf']=bin2hex(random_bytes(32));
$expired=$quote&&$quote['status']!=='accepted'&&strtotime($quote['valid_until'])<strtotime(date('Y-m-d'));$status=$expired?'expired':($quote['status']??'draft');$meta=quote_status_meta($status);$response=(string)($_GET['respuesta']??'');
?>
<!doctype html><html lang="es-CL"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow,noarchive"><meta name="theme-color" content="#07111f"><title><?= $quote?e($quote['quote_number']).' | Go Creative':'Cotización no disponible' ?></title><link rel="icon" href="<?= e(site_path('/assets/img/favicon.svg')) ?>" type="image/svg+xml"><link rel="stylesheet" href="<?= e(site_path('/assets/css/quote-public.css?v=1.0.0')) ?>"></head><body>
<header class="quote-public-header"><a href="<?= e(site_path('/')) ?>"><img src="<?= e(site_path('/assets/img/logo-white.webp')) ?>" width="620" height="224" alt="Go Creative Chile"></a><span>Propuesta comercial</span></header>
<main class="quote-public-main">
<?php if($quote):?>
<section class="quote-public-intro"><span class="quote-public-eyebrow"><?= e($quote['quote_number']) ?> · <?= e(date('d-m-Y',strtotime($quote['issue_date']))) ?></span><h1><?= e($quote['title']) ?></h1><p><?= e($quote['introduction']??'Propuesta preparada especialmente para tu proyecto.') ?></p><div class="quote-public-meta"><span>Preparada para<strong><?= e($quote['customer_name']) ?></strong></span><span>Válida hasta<strong><?= e(date('d-m-Y',strtotime($quote['valid_until']))) ?></strong></span><span>Estado<strong class="quote-state quote-state--<?= e($meta['class']) ?>"><?= e($meta['label']) ?></strong></span></div></section>
<?php if($response==='ok'):?><div class="quote-response-success">Tu respuesta quedó registrada. Go Creative se comunicará contigo para coordinar los siguientes pasos.</div><?php endif;?>
<div class="quote-public-grid"><section class="quote-public-card"><div class="quote-public-card__head"><h2>Detalle de la propuesta</h2><span><?= count($items) ?> ítems</span></div><div class="quote-public-items"><?php foreach($items as $item):?><article><span><?= $item['item_type']==='product'?'Producto':'Servicio' ?></span><div><h3><?= e($item['name']) ?></h3><?php if($item['description']):?><p><?= nl2br(e($item['description'])) ?></p><?php endif;?></div><small><?= rtrim(rtrim(number_format((float)$item['quantity'],2,',','.'),'0'),',') ?> × $<?= number_format((int)$item['unit_price'],0,',','.') ?></small><strong>$<?= number_format((int)$item['line_total'],0,',','.') ?></strong></article><?php endforeach;?></div></section>
<aside><section class="quote-total-card"><span>Total propuesta</span><strong><?= e(payment_format_amount((int)$quote['total'],$quote['currency'])) ?></strong><dl><div><dt>Subtotal</dt><dd>$<?= number_format((int)$quote['subtotal'],0,',','.') ?></dd></div><?php if((int)$quote['discount_amount']>0):?><div><dt>Descuento</dt><dd>- $<?= number_format((int)$quote['discount_amount'],0,',','.') ?></dd></div><?php endif;?><div><dt>IVA <?= (int)$quote['tax_percent'] ?>%</dt><dd>$<?= number_format((int)$quote['tax_amount'],0,',','.') ?></dd></div></dl><a class="quote-download" href="<?= e(site_path('/cotizacion/pdf.php?codigo='.rawurlencode($quote['public_key']))) ?>">Descargar propuesta PDF ↓</a></section>
<?php if(in_array($status,['draft','sent'],true)&&!$expired):?><section class="quote-answer-card"><h2>¿Avanzamos?</h2><p>Registra tu decisión. También puedes responder el correo si necesitas ajustes.</p><div class="quote-answer-actions"><form method="post" action="<?= e(site_path('/cotizacion/responder.php')) ?>"><input type="hidden" name="csrf_token" value="<?= e($_SESSION['quote_csrf']) ?>"><input type="hidden" name="codigo" value="<?= e($quote['public_key']) ?>"><input type="hidden" name="action" value="accepted"><button class="quote-accept">Aceptar propuesta →</button></form><form method="post" action="<?= e(site_path('/cotizacion/responder.php')) ?>"><input type="hidden" name="csrf_token" value="<?= e($_SESSION['quote_csrf']) ?>"><input type="hidden" name="codigo" value="<?= e($quote['public_key']) ?>"><input type="hidden" name="action" value="rejected"><button class="quote-reject">No aceptar</button></form></div></section><?php endif;?></aside></div>
<?php if($quote['terms']||$quote['notes']):?><section class="quote-conditions"><?php if($quote['terms']):?><div><span>Condiciones comerciales</span><p><?= nl2br(e($quote['terms'])) ?></p></div><?php endif;?><?php if($quote['notes']):?><div><span>Observaciones</span><p><?= nl2br(e($quote['notes'])) ?></p></div><?php endif;?></section><?php endif;?>
<?php else:?><section class="quote-not-found"><span class="quote-public-eyebrow"><?= $serviceError?'Servicio temporalmente no disponible':'Enlace no válido' ?></span><h1>No pudimos abrir esta cotización.</h1><p>Solicita a Go Creative un nuevo enlace o inténtalo nuevamente más tarde.</p><a href="<?= e(whatsapp_url('Hola Go Creative, necesito ayuda con una cotización.')) ?>">Contactar por WhatsApp →</a></section><?php endif;?>
</main><footer class="quote-public-footer"><span>© <?= date('Y') ?> Go Creative Chile</span><span>Propuesta privada · no indexada</span></footer></body></html>
