<?php
$meta = ['title' => 'Servicios digitales para empresas en Chile | Go Creative', 'description' => 'Diseño web, ecommerce, software a medida, automatización, Meta Ads, diseño creativo y soporte técnico para empresas en Chile.', 'path' => '/servicios/'];
$active = 'servicios';
require dirname(__DIR__) . '/includes/header.php';
?>
<section class="inner-hero"><div class="container"><div class="breadcrumbs"><a href="/">Inicio</a><span>/</span><span>Servicios</span></div><div class="inner-hero__grid"><div><p class="eyebrow"><span></span> Soluciones digitales</p><h1>Servicios que convierten problemas en <em>ventajas reales.</em></h1><p class="inner-hero__lead">Combinamos estrategia, diseño y desarrollo para mejorar la presencia comercial y la operación de empresas en Chile.</p></div><div class="inner-hero__aside"><p>Podemos comenzar por una necesidad puntual y construir una base preparada para sumar nuevas funciones a medida que tu negocio crece.</p><a class="text-link" href="/contacto/">Solicitar orientación <span>→</span></a></div></div></div></section>
<section class="section"><div class="container"><div class="section-heading section-heading--center" data-reveal><p class="eyebrow eyebrow--dark"><span></span> Capacidades</p><h2>Una sola agencia para conectar imagen, ventas y operación.</h2><p>El objetivo no es sumar tecnología por sumar: es resolver fricciones, entregar control y facilitar que clientes y equipos avancen.</p></div><div class="service-grid">
<?php $services = [
['01','/diseno-web-chile/','↗','Diseño y desarrollo web','Sitios corporativos, landing pages y páginas autoadministrables con estructura comercial, SEO y versión móvil.'],
['02','/tiendas-online/','⌁','Tiendas online','Ecommerce con catálogo, carrito, pagos, envíos, pedidos y panel de administración.'],
['03','/software-a-medida/','⌘','Software a medida','Sistemas de gestión, inventario, reservas, ventas, documentos, reportes y permisos.'],
['04','/automatizacion/','⚡','Automatización de procesos','Flujos, alertas, correos, aprobaciones y documentos automáticos conectados a tus datos.'],
['05','/meta-ads/','◎','Meta Ads','Campañas en Facebook e Instagram enfocadas en consultas, WhatsApp y oportunidades medibles.'],
['06','/diseno-creativo-digital/','✦','Diseño creativo digital','Identidad visual, banners, gráficas y recursos que fortalecen la presencia de tu marca.'],
['07','/soporte-tecnico/','✓','Soporte técnico','Mantenimiento, recuperación, optimización, migración y seguridad para sitios y sistemas.'],
]; foreach($services as $s): ?>
<a class="service-card" href="<?= e($s[1]) ?>" data-reveal><span class="service-card__number"><?= e($s[0]) ?></span><div class="service-card__icon"><?= e($s[2]) ?></div><h3><?= e($s[3]) ?></h3><p><?= e($s[4]) ?></p><strong>Ver servicio <span>→</span></strong></a>
<?php endforeach; ?>
</div></div></section>
<section class="section section--mist"><div class="container content-grid"><div class="content-grid__intro" data-reveal><p class="eyebrow eyebrow--dark"><span></span> Cómo elegimos</p><h2>La solución correcta parte por una buena pregunta.</h2><p>Antes de recomendar una web, campaña o sistema, revisamos qué resultado necesita el negocio y dónde está hoy la mayor fricción.</p></div><div class="content-stack" data-reveal><article class="content-item"><span>01</span><div><h3>¿Necesitas captar clientes?</h3><p>Una web profesional y campañas medibles pueden ordenar tu propuesta y generar nuevas conversaciones.</p></div></article><article class="content-item"><span>02</span><div><h3>¿Necesitas vender online?</h3><p>Una tienda bien configurada conecta catálogo, pago, despacho, pedidos y administración.</p></div></article><article class="content-item"><span>03</span><div><h3>¿Necesitas recuperar tiempo?</h3><p>La automatización elimina tareas repetitivas y conecta la información que hoy se traspasa a mano.</p></div></article><article class="content-item"><span>04</span><div><h3>¿Necesitas control operativo?</h3><p>Un sistema a medida centraliza datos, responsables, estados, permisos, reportes e indicadores.</p></div></article></div></div></section>
<section class="cta-band"><div class="container cta-band__inner"><div><p class="eyebrow"><span></span> Hablemos</p><h2>Cuéntanos qué quieres mejorar.</h2><p>Revisaremos tu necesidad y te ayudaremos a definir el siguiente paso.</p></div><div class="cta-band__actions"><a class="button button--lime" href="/contacto/">Solicitar evaluación <span>↗</span></a></div></div></section>
<?php require dirname(__DIR__) . '/includes/footer.php'; ?>
