<?php
$meta = ['title' => 'Campañas Meta Ads en Chile | Facebook e Instagram', 'description' => 'Gestión de campañas en Facebook e Instagram con estrategia, segmentación, anuncios, Meta Pixel y optimización por resultados.', 'path' => '/meta-ads/'];
$active = 'servicios';
require dirname(__DIR__) . '/includes/header.php';
?>
<section class="inner-hero"><div class="container"><div class="breadcrumbs"><a href="/">Inicio</a><span>/</span><a href="/servicios/">Servicios</a><span>/</span><span>Meta Ads</span></div><div class="inner-hero__grid"><div><p class="eyebrow"><span></span> Facebook e Instagram Ads</p><h1>Campañas que buscan oportunidades, no solo <em>clics.</em></h1><p class="inner-hero__lead">Planificamos y administramos publicidad para atraer consultas, conversaciones por WhatsApp y acciones comerciales que puedan medirse.</p></div><div class="inner-hero__aside"><p>Definimos objetivo, público, oferta, piezas, destino y medición antes de comenzar a invertir.</p><a class="text-link" href="/contacto/">Evaluar campaña <span>→</span></a></div></div></div></section>
<section class="section"><div class="container"><div class="section-heading section-heading--center"><p class="eyebrow eyebrow--dark"><span></span> Gestión estratégica</p><h2>Una estructura clara desde el anuncio hasta la conversión.</h2><p>La inversión publicitaria se paga directamente a Meta y se define por separado del servicio de gestión.</p></div><div class="feature-grid"><article class="feature-card"><div class="feature-card__icon">01</div><h3>Estrategia y segmentación</h3><p>Objetivo, audiencias, presupuesto, ubicación y estructura de campañas.</p></article><article class="feature-card"><div class="feature-card__icon">02</div><h3>Anuncios y destinos</h3><p>Piezas para Facebook e Instagram dirigidas a web, formulario o WhatsApp.</p></article><article class="feature-card"><div class="feature-card__icon">03</div><h3>Medición y optimización</h3><p>Meta Pixel, eventos, conversiones y ajustes según resultados comerciales.</p></article></div></div></section>
<section class="section section--mist"><div class="container content-grid"><div class="content-grid__intro"><p class="eyebrow eyebrow--dark"><span></span> Lo importante</p><h2>Publicidad y experiencia deben trabajar juntas.</h2><p>Una campaña puede atraer personas, pero el destino debe transmitir confianza, responder dudas y facilitar el contacto.</p></div><div class="content-stack"><article class="content-item"><span>01</span><div><h3>Oferta clara</h3><p>El cliente debe entender qué recibe, por qué le conviene y qué debe hacer después.</p></div></article><article class="content-item"><span>02</span><div><h3>Página o WhatsApp preparados</h3><p>El recorrido continúa después del clic con información, velocidad y atención coherentes.</p></div></article><article class="content-item"><span>03</span><div><h3>Datos para decidir</h3><p>Medimos consultas, conversaciones y conversiones para optimizar con criterio comercial.</p></div></article></div></div></section>
<section class="cta-band"><div class="container cta-band__inner"><div><h2>Atrae oportunidades con campañas medibles.</h2><p>Cuéntanos qué vendes, a quién quieres llegar y qué resultado esperas.</p></div><div class="cta-band__actions"><a class="button button--lime" href="/contacto/">Solicitar evaluación <span>↗</span></a></div></div></section>
<?php require dirname(__DIR__) . '/includes/footer.php'; ?>
